upstream collabboard_backends {
    ip_hash;
    server backend-1:8000;
    server backend-2:8000;
}

server {
    listen 80;
    server_name collabboard.lixyon.me;
    server_tokens off;
    
    set_real_ip_from 127.0.0.1;
    real_ip_header CF-Connecting-IP;

    location / {
        proxy_pass http://collabboard_backends;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /ws {
        proxy_pass http://collabboard_backends;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location /health {
        proxy_pass http://collabboard_backends;
        proxy_set_header X-Forwarded-Proto https;
    }
}
